### ISSUE TITLE
Inhalte

### ISSUE THREAD

**Issue by Stura7** [TacticalTrainingTeam/ttt_handbuch#30]
Die folgende Struktur die in #16 vorgeschlagen wurde, wurde übernommen. Jedoch müssen die einzelnen Abschnitte überprüft bzw. verfasst werden
- [ ] Einleitung #38
- [x] Truppenordnung #39
  - [x] OPL #40
  - [x] Zugführung #41
  - [x] Infanterie #42
  - [x] Spezialeinheiten #43
  - [ ] Logistik/MedEvac #44
  - [ ] CAS #45
  - [ ] Mechanisierte Infanterie #46
  - [ ] Kampfpanzer #47
  - [ ] Artillerie #48
- [ ] Grundlagen #49
  - [x] Formationen #50
  - [x] Sicherungen #51
  - [x] Buddy-System #52
  - [x] Manöver / Bewegen im Gelände #53
  - [x] Funken / Kommunikation #54
  - [x] Auf-/Absitzen #55
  - [x] Erste Hilfe #56
  - [x] Verhalten bei Feindkontakt #57
- [ ] Fortgeschrittenes #58
  - [ ] Führen #59
    - [ ] als OPL #60
    - [ ] als Zugführer #61
    - [ ] als Truppführer #62
  - [x] Logistik/MedEvac anfordern (5-Liner) #63
  - [ ] CAS anfordern (5-Liner/9-Liner) #64
  - [ ] Artillerie anfordern (5-Liner) #65
  - [ ] Close Quarters Combat (CQB) #66
  - [x] Hubschrauber und Infanterie #67
  - [ ] Sani, Sani! #68
  - [ ] Konvoi #69
- [ ] Tutorials #70 
  - [ ] Drohnen
  - [ ] ACE-Geräte
  - [ ] TFAR #71
  - [ ] CAS #72
  - [ ] Artillerie #22
- [ ] Sonstiges #73 

Gerade die Abschnitte Truppengattungen und Grundlagen sollten sich dabei in den einzelnen Abschnitten sehr kurz halten und pro Unterabschnitt maximal 3 Seiten lang sein, wobei eine Seite davon eine Art "Merkblatt" sein sollte (z.B. eine grafische Übersicht aller Formationen). Bei den Truppengattungen dürfte das teilweise auch auf einer Seite zu lösen sein. Generell möchte ich viel mit Merkblättern arbeiten, die das wichtigste zusammenfassen, und nur in dem Bereich "Tutorials" sehr ausführlich werden - z.B. mit dem Funkhandbuch oder dem JTAC-Handbuch. Ist jemand von den hier Beteiligten in der Erstellung von Grafiken mit Photoshop & Co bewandert?

**Comment by Stura7** [comment]
Conen falls du dann Zeit wieder hast, kannst du bitte mal Anmerken, welche Punkte soweit in Ordnung sind und welche noch überarbeitet werden müssen.
Vielen Dank im Voraus.

**Comment by Stura7** [comment]
@TheConen bin gerade noch an optimieren der Dokumente. Jedoch gestaltet sich dies schwierig da alle Dokumente "Content" heißen. Es geht zwar, aber ist eigentlich sehr unleserlich.

**Comment by TheConen** [comment]
Die Idee mit dem "content" war, in jedem Ordner eine Datei zu haben, die
 - entweder direkt den kompletten Kapitelinhalt enthält
 - oder, bei mehreren Dateien, diese einbindet
sodass man immer ein Wurzeldokument hat, welches man in der obersten Ebene einbinden kann.

**Comment by Stura7** [comment]
![content](https://cloud.githubusercontent.com/assets/12585832/9218026/075b248c-40cf-11e5-9b0c-f1e6279b3c5d.PNG)
Der Sinn der Idee ist mir klar, nur entsteht wie zu sehen folgendes Problem, es treten Fehlermeldung in verschiedenen Dokumenten auf, jedoch wird nur der Dateiname angegeben. Zwar kann man nur Fehlerstelle springen, weiß jedoch dann nicht wo man sich im Dokument aktuell befindet 
![content2](https://cloud.githubusercontent.com/assets/12585832/9218079/705f3298-40cf-11e5-9c33-aa2838e39e9a.PNG)
Des Weiteren kann es so bei der Optimierung schwierig sein die einzelnen Dokument (siehe Tab-Leiste) auseinander zu halten.
Vielleicht kann man dies irrgendwie besser gestalten.
